# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-09-07 06:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(blank=True, max_length=255, null=True)),
                ('machine_make', models.CharField(blank=True, max_length=255, null=True)),
                ('machine_model', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('machine_barcode', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('machine_serial_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('machine_service_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('machine_warranty', models.IntegerField(default=0)),
                ('machine_endoflife', models.DateField(blank=True, max_length=20, null=True)),
                ('machine_workstation_name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('machine_domain', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_asset_owned_by', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_purchase_date', models.DateField(blank=True, max_length=20, null=True)),
                ('machine_acquisition_date', models.DateField(blank=True, max_length=20, null=True)),
                ('machine_return_date', models.DateField(blank=True, max_length=20, null=True)),
                ('machine_invoice_number', models.IntegerField(default=0)),
                ('machine_status', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_location', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_desk_number', models.IntegerField(default=0)),
                ('machine_cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_ram', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('machine_hdd', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('machine_gpu', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('machine_os', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
